[package]
name = "audionoise-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
_core = { package = "audionoise", path = "../core" }
ratatui = "0.30"
crossterm = "0.29"
clap = { version = "4.5", features = ["derive"] }
